services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chatapp
      - JWT_SECRET=your_jwt_secret_here
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"